version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "webjema/crawler1"
    IMAGE_TAG: "prod"
  secrets-manager:
    dockerhubcredentials: arn:aws:secretsmanager:eu-west-1:004161417279:secret:docker-hub-AkBKhk

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub with credentials $dockerhubcredentials
      - eval $(echo $dockerhubcredentials | sed -e 's/{/export /' -e 's/}//' -e 's/:/=/g' -e "s/,/; export /g")
      - docker login --username=$user --password=$password
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"CrawlerContainer","imageUri":"%s"}]' registry.hub.docker.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files: imagedefinitions.json