version: 0.2

env:
  secrets-manager:
    docker-hub-credentials: arn:aws:secretsmanager:eu-west-1:004161417279:secret:docker-hub-AkBKhk

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub with credentials $docker-hub-credentials
      - docker login --username=$docker-hub-credentials.user --password=$docker-hub-credentials.password
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG